name: Run Release Drafter
on:
  push:
    branches: [ master ]

permissions:
  releases: write
  contents: write
  pull-requests: write
  id-token: write

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
